name: lifepo4
base: core18
version: '1.1'
summary: LifePO4wered

description: |
  Use this snap to power supply WDT reboot rpi 
  
grade: devel
confinement: strict

layout:
  /usr/local:
    bind: $SNAP/usr/local
  /etc:
    bind: $SNAP/etc

parts:      
   lifepo4:
    source:  .
    source-type: git
    plugin: make
    make-parameters:
       - all
       - USE_SYSTEMD=0
    build-packages:
       - libsystemd-dev
       - lsb-base

architectures:
  - build-on: armhf
    run-on: armhf
  - build-on: arm64
    run-on: arm64

apps:
  init:
      daemon: simple
      command: lifepo4wered-daemon start
      plugs:
         - shutdown
         - i2c
         - daemon-notify
         
         
  lifepo4:
       command: lifepo4wered-cli
       plugs:
         - shutdown
         - i2c
